### ISSUE TITLE
Indexing for Kohana 3.3 modules

### ISSUE THREAD

**Issue by gevans** [ahutchings/kohana-modules#117]
[Kohana 3.3.0 was released](http://forum.kohanaframework.org/discussion/11191/kohana-3-3-0-released) a couple days ago.

Can you guess who can't wait to start sending some pull requests with compatible modules?

**Edit**: Not sure if this is actually an issue for the kohana-modules.com repo...

**Comment by ahutchings** [comment]
The website gets the available versions from this repo's branches, so you had the right place. The 3.3 branch is ready for pull requests now - go nuts!
