### ISSUE TITLE
Site update frequency

### ISSUE THREAD

**Issue by pocesar** [ahutchings/kohana-modules#154]
The site doesn't get updated as soon there's a new module here? It seems that the last update online is from almost 1 month ago. Consider using gh-pages to make it as quick as 10 min to become online :+1:

**Comment by ahutchings** [comment]
The site should update as soon as new modules are added via a repository WebHook URL, but that seems to have broken recently. I'll get that fixed asap.

Thanks for bringing it to my attention!

**Comment by pocesar** [comment]
no problem! thanks for helping the Kohana community :D
