### ISSUE TITLE
3.1 Base

### ISSUE THREAD

**Issue by nexeck** [ahutchings/kohana-modules#8]
https://github.com/kohana/database
The Name should be database

**Comment by ahutchings** [comment]
It looks like this may be an issue with the way GitHub creates their submodule links in the file listing. I created an issue here: http://support.github.com/discussions/site/3082-incorrect-submodule-link-in-file-listing

**Comment by ahutchings** [comment]
This was an issue on GitHub's end, and has been fixed now. See the link above for details.
